#!/bin/bash

set -e

MACHTYPE="$(uname -m)"
case "${MACHTYPE}" in
  armv6l) ;&
  armv7l) MACHTYPE=arm ;;
  *) ;;
esac

export ALCOVE_INCLUDE="${ALCOVE_INCLUDE-/usr/local/lib}"
export ALCOVE_LDFLAGS="-I$ALCOVE_INCLUDE/kernel-headers/generic/include -I$ALCOVE_INCLUDE/kernel-headers/${MACHTYPE}/include"
export ALCOVE_CFLAGS="-g -Wall -fwrapv -pedantic -no-pie -Wshadow -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes"
export CC="musl-gcc -static -Os"
exec make $@
