/* Copyright (c) 2014-2021, Michael Santos <michael.santos@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
static const alcove_constant_t alcove_prctl_constants[] = {
#ifdef PR_CAPBSET_DROP
    ALCOVE_CONSTANT(PR_CAPBSET_DROP),
#endif
#ifdef PR_CAPBSET_READ
    ALCOVE_CONSTANT(PR_CAPBSET_READ),
#endif
#ifdef PR_CAP_AMBIENT
    ALCOVE_CONSTANT(PR_CAP_AMBIENT),
#endif
#ifdef PR_CAP_AMBIENT_CLEAR_ALL
    ALCOVE_CONSTANT(PR_CAP_AMBIENT_CLEAR_ALL),
#endif
#ifdef PR_CAP_AMBIENT_IS_SET
    ALCOVE_CONSTANT(PR_CAP_AMBIENT_IS_SET),
#endif
#ifdef PR_CAP_AMBIENT_LOWER
    ALCOVE_CONSTANT(PR_CAP_AMBIENT_LOWER),
#endif
#ifdef PR_CAP_AMBIENT_RAISE
    ALCOVE_CONSTANT(PR_CAP_AMBIENT_RAISE),
#endif
#ifdef PR_ENDIAN_BIG
    ALCOVE_CONSTANT(PR_ENDIAN_BIG),
#endif
#ifdef PR_ENDIAN_LITTLE
    ALCOVE_CONSTANT(PR_ENDIAN_LITTLE),
#endif
#ifdef PR_ENDIAN_PPC_LITTLE
    ALCOVE_CONSTANT(PR_ENDIAN_PPC_LITTLE),
#endif
#ifdef PR_FPEMU_NOPRINT
    ALCOVE_CONSTANT(PR_FPEMU_NOPRINT),
#endif
#ifdef PR_FPEMU_SIGFPE
    ALCOVE_CONSTANT(PR_FPEMU_SIGFPE),
#endif
#ifdef PR_FP_EXC_ASYNC
    ALCOVE_CONSTANT(PR_FP_EXC_ASYNC),
#endif
#ifdef PR_FP_EXC_DISABLED
    ALCOVE_CONSTANT(PR_FP_EXC_DISABLED),
#endif
#ifdef PR_FP_EXC_DIV
    ALCOVE_CONSTANT(PR_FP_EXC_DIV),
#endif
#ifdef PR_FP_EXC_INV
    ALCOVE_CONSTANT(PR_FP_EXC_INV),
#endif
#ifdef PR_FP_EXC_NONRECOV
    ALCOVE_CONSTANT(PR_FP_EXC_NONRECOV),
#endif
#ifdef PR_FP_EXC_OVF
    ALCOVE_CONSTANT(PR_FP_EXC_OVF),
#endif
#ifdef PR_FP_EXC_PRECISE
    ALCOVE_CONSTANT(PR_FP_EXC_PRECISE),
#endif
#ifdef PR_FP_EXC_RES
    ALCOVE_CONSTANT(PR_FP_EXC_RES),
#endif
#ifdef PR_FP_EXC_SW_ENABLE
    ALCOVE_CONSTANT(PR_FP_EXC_SW_ENABLE),
#endif
#ifdef PR_FP_EXC_UND
    ALCOVE_CONSTANT(PR_FP_EXC_UND),
#endif
#ifdef PR_FP_MODE_FR
    ALCOVE_CONSTANT(PR_FP_MODE_FR),
#endif
#ifdef PR_FP_MODE_FRE
    ALCOVE_CONSTANT(PR_FP_MODE_FRE),
#endif
#ifdef PR_GET_CHILD_SUBREAPER
    ALCOVE_CONSTANT(PR_GET_CHILD_SUBREAPER),
#endif
#ifdef PR_GET_DUMPABLE
    ALCOVE_CONSTANT(PR_GET_DUMPABLE),
#endif
#ifdef PR_GET_ENDIAN
    ALCOVE_CONSTANT(PR_GET_ENDIAN),
#endif
#ifdef PR_GET_FPEMU
    ALCOVE_CONSTANT(PR_GET_FPEMU),
#endif
#ifdef PR_GET_FPEXC
    ALCOVE_CONSTANT(PR_GET_FPEXC),
#endif
#ifdef PR_GET_FP_MODE
    ALCOVE_CONSTANT(PR_GET_FP_MODE),
#endif
#ifdef PR_GET_KEEPCAPS
    ALCOVE_CONSTANT(PR_GET_KEEPCAPS),
#endif
#ifdef PR_GET_NAME
    ALCOVE_CONSTANT(PR_GET_NAME),
#endif
#ifdef PR_GET_NO_NEW_PRIVS
    ALCOVE_CONSTANT(PR_GET_NO_NEW_PRIVS),
#endif
#ifdef PR_GET_PDEATHSIG
    ALCOVE_CONSTANT(PR_GET_PDEATHSIG),
#endif
#ifdef PR_GET_SECCOMP
    ALCOVE_CONSTANT(PR_GET_SECCOMP),
#endif
#ifdef PR_GET_SECUREBITS
    ALCOVE_CONSTANT(PR_GET_SECUREBITS),
#endif
#ifdef PR_GET_SPECULATION_CTRL
    ALCOVE_CONSTANT(PR_GET_SPECULATION_CTRL),
#endif
#ifdef PR_GET_TAGGED_ADDR_CTRL
    ALCOVE_CONSTANT(PR_GET_TAGGED_ADDR_CTRL),
#endif
#ifdef PR_GET_THP_DISABLE
    ALCOVE_CONSTANT(PR_GET_THP_DISABLE),
#endif
#ifdef PR_GET_TID_ADDRESS
    ALCOVE_CONSTANT(PR_GET_TID_ADDRESS),
#endif
#ifdef PR_GET_TIMERSLACK
    ALCOVE_CONSTANT(PR_GET_TIMERSLACK),
#endif
#ifdef PR_GET_TIMING
    ALCOVE_CONSTANT(PR_GET_TIMING),
#endif
#ifdef PR_GET_TSC
    ALCOVE_CONSTANT(PR_GET_TSC),
#endif
#ifdef PR_GET_UNALIGN
    ALCOVE_CONSTANT(PR_GET_UNALIGN),
#endif
#ifdef PR_MCE_KILL
    ALCOVE_CONSTANT(PR_MCE_KILL),
#endif
#ifdef PR_MCE_KILL_CLEAR
    ALCOVE_CONSTANT(PR_MCE_KILL_CLEAR),
#endif
#ifdef PR_MCE_KILL_DEFAULT
    ALCOVE_CONSTANT(PR_MCE_KILL_DEFAULT),
#endif
#ifdef PR_MCE_KILL_EARLY
    ALCOVE_CONSTANT(PR_MCE_KILL_EARLY),
#endif
#ifdef PR_MCE_KILL_GET
    ALCOVE_CONSTANT(PR_MCE_KILL_GET),
#endif
#ifdef PR_MCE_KILL_LATE
    ALCOVE_CONSTANT(PR_MCE_KILL_LATE),
#endif
#ifdef PR_MCE_KILL_SET
    ALCOVE_CONSTANT(PR_MCE_KILL_SET),
#endif
#ifdef PR_MPX_DISABLE_MANAGEMENT
    ALCOVE_CONSTANT(PR_MPX_DISABLE_MANAGEMENT),
#endif
#ifdef PR_MPX_ENABLE_MANAGEMENT
    ALCOVE_CONSTANT(PR_MPX_ENABLE_MANAGEMENT),
#endif
#ifdef PR_PAC_APDAKEY
    ALCOVE_CONSTANT(PR_PAC_APDAKEY),
#endif
#ifdef PR_PAC_APDBKEY
    ALCOVE_CONSTANT(PR_PAC_APDBKEY),
#endif
#ifdef PR_PAC_APGAKEY
    ALCOVE_CONSTANT(PR_PAC_APGAKEY),
#endif
#ifdef PR_PAC_APIAKEY
    ALCOVE_CONSTANT(PR_PAC_APIAKEY),
#endif
#ifdef PR_PAC_APIBKEY
    ALCOVE_CONSTANT(PR_PAC_APIBKEY),
#endif
#ifdef PR_PAC_RESET_KEYS
    ALCOVE_CONSTANT(PR_PAC_RESET_KEYS),
#endif
#ifdef PR_SET
    ALCOVE_CONSTANT(PR_SET),
#endif
#ifdef PR_SET_CHILD_SUBREAPER
    ALCOVE_CONSTANT(PR_SET_CHILD_SUBREAPER),
#endif
#ifdef PR_SET_DUMPABLE
    ALCOVE_CONSTANT(PR_SET_DUMPABLE),
#endif
#ifdef PR_SET_ENDIAN
    ALCOVE_CONSTANT(PR_SET_ENDIAN),
#endif
#ifdef PR_SET_FPEMU
    ALCOVE_CONSTANT(PR_SET_FPEMU),
#endif
#ifdef PR_SET_FPEXC
    ALCOVE_CONSTANT(PR_SET_FPEXC),
#endif
#ifdef PR_SET_FP_MODE
    ALCOVE_CONSTANT(PR_SET_FP_MODE),
#endif
#ifdef PR_SET_KEEPCAPS
    ALCOVE_CONSTANT(PR_SET_KEEPCAPS),
#endif
#ifdef PR_SET_MM
    ALCOVE_CONSTANT(PR_SET_MM),
#endif
#ifdef PR_SET_MM_ARG_END
    ALCOVE_CONSTANT(PR_SET_MM_ARG_END),
#endif
#ifdef PR_SET_MM_ARG_START
    ALCOVE_CONSTANT(PR_SET_MM_ARG_START),
#endif
#ifdef PR_SET_MM_AUXV
    ALCOVE_CONSTANT(PR_SET_MM_AUXV),
#endif
#ifdef PR_SET_MM_BRK
    ALCOVE_CONSTANT(PR_SET_MM_BRK),
#endif
#ifdef PR_SET_MM_END_CODE
    ALCOVE_CONSTANT(PR_SET_MM_END_CODE),
#endif
#ifdef PR_SET_MM_END_DATA
    ALCOVE_CONSTANT(PR_SET_MM_END_DATA),
#endif
#ifdef PR_SET_MM_ENV_END
    ALCOVE_CONSTANT(PR_SET_MM_ENV_END),
#endif
#ifdef PR_SET_MM_ENV_START
    ALCOVE_CONSTANT(PR_SET_MM_ENV_START),
#endif
#ifdef PR_SET_MM_EXE_FILE
    ALCOVE_CONSTANT(PR_SET_MM_EXE_FILE),
#endif
#ifdef PR_SET_MM_MAP
    ALCOVE_CONSTANT(PR_SET_MM_MAP),
#endif
#ifdef PR_SET_MM_MAP_SIZE
    ALCOVE_CONSTANT(PR_SET_MM_MAP_SIZE),
#endif
#ifdef PR_SET_MM_START_BRK
    ALCOVE_CONSTANT(PR_SET_MM_START_BRK),
#endif
#ifdef PR_SET_MM_START_CODE
    ALCOVE_CONSTANT(PR_SET_MM_START_CODE),
#endif
#ifdef PR_SET_MM_START_DATA
    ALCOVE_CONSTANT(PR_SET_MM_START_DATA),
#endif
#ifdef PR_SET_MM_START_STACK
    ALCOVE_CONSTANT(PR_SET_MM_START_STACK),
#endif
#ifdef PR_SET_NAME
    ALCOVE_CONSTANT(PR_SET_NAME),
#endif
#ifdef PR_SET_NO_NEW_PRIVS
    ALCOVE_CONSTANT(PR_SET_NO_NEW_PRIVS),
#endif
#ifdef PR_SET_PDEATHSIG
    ALCOVE_CONSTANT(PR_SET_PDEATHSIG),
#endif
#ifdef PR_SET_PTRACER
    ALCOVE_CONSTANT(PR_SET_PTRACER),
#endif
#ifdef PR_SET_PTRACER_ANY
    ALCOVE_CONSTANT(PR_SET_PTRACER_ANY),
#endif
#ifdef PR_SET_SECCOMP
    ALCOVE_CONSTANT(PR_SET_SECCOMP),
#endif
#ifdef PR_SET_SECUREBITS
    ALCOVE_CONSTANT(PR_SET_SECUREBITS),
#endif
#ifdef PR_SET_SPECULATION_CTRL
    ALCOVE_CONSTANT(PR_SET_SPECULATION_CTRL),
#endif
#ifdef PR_SET_TAGGED_ADDR_CTRL
    ALCOVE_CONSTANT(PR_SET_TAGGED_ADDR_CTRL),
#endif
#ifdef PR_SET_THP_DISABLE
    ALCOVE_CONSTANT(PR_SET_THP_DISABLE),
#endif
#ifdef PR_SET_TIMERSLACK
    ALCOVE_CONSTANT(PR_SET_TIMERSLACK),
#endif
#ifdef PR_SET_TIMING
    ALCOVE_CONSTANT(PR_SET_TIMING),
#endif
#ifdef PR_SET_TSC
    ALCOVE_CONSTANT(PR_SET_TSC),
#endif
#ifdef PR_SET_UNALIGN
    ALCOVE_CONSTANT(PR_SET_UNALIGN),
#endif
#ifdef PR_SPEC_DISABLE
    ALCOVE_CONSTANT(PR_SPEC_DISABLE),
#endif
#ifdef PR_SPEC_DISABLE_NOEXEC
    ALCOVE_CONSTANT(PR_SPEC_DISABLE_NOEXEC),
#endif
#ifdef PR_SPEC_ENABLE
    ALCOVE_CONSTANT(PR_SPEC_ENABLE),
#endif
#ifdef PR_SPEC_FORCE_DISABLE
    ALCOVE_CONSTANT(PR_SPEC_FORCE_DISABLE),
#endif
#ifdef PR_SPEC_INDIRECT_BRANCH
    ALCOVE_CONSTANT(PR_SPEC_INDIRECT_BRANCH),
#endif
#ifdef PR_SPEC_NOT_AFFECTED
    ALCOVE_CONSTANT(PR_SPEC_NOT_AFFECTED),
#endif
#ifdef PR_SPEC_PRCTL
    ALCOVE_CONSTANT(PR_SPEC_PRCTL),
#endif
#ifdef PR_SPEC_STORE_BYPASS
    ALCOVE_CONSTANT(PR_SPEC_STORE_BYPASS),
#endif
#ifdef PR_SVE_GET_VL
    ALCOVE_CONSTANT(PR_SVE_GET_VL),
#endif
#ifdef PR_SVE_SET_VL
    ALCOVE_CONSTANT(PR_SVE_SET_VL),
#endif
#ifdef PR_SVE_SET_VL_ONEXEC
    ALCOVE_CONSTANT(PR_SVE_SET_VL_ONEXEC),
#endif
#ifdef PR_SVE_VL_INHERIT
    ALCOVE_CONSTANT(PR_SVE_VL_INHERIT),
#endif
#ifdef PR_SVE_VL_LEN_MASK
    ALCOVE_CONSTANT(PR_SVE_VL_LEN_MASK),
#endif
#ifdef PR_TAGGED_ADDR_ENABLE
    ALCOVE_CONSTANT(PR_TAGGED_ADDR_ENABLE),
#endif
#ifdef PR_TASK_PERF_EVENTS_DISABLE
    ALCOVE_CONSTANT(PR_TASK_PERF_EVENTS_DISABLE),
#endif
#ifdef PR_TASK_PERF_EVENTS_ENABLE
    ALCOVE_CONSTANT(PR_TASK_PERF_EVENTS_ENABLE),
#endif
#ifdef PR_TIMING_STATISTICAL
    ALCOVE_CONSTANT(PR_TIMING_STATISTICAL),
#endif
#ifdef PR_TIMING_TIMESTAMP
    ALCOVE_CONSTANT(PR_TIMING_TIMESTAMP),
#endif
#ifdef PR_TSC_ENABLE
    ALCOVE_CONSTANT(PR_TSC_ENABLE),
#endif
#ifdef PR_TSC_SIGSEGV
    ALCOVE_CONSTANT(PR_TSC_SIGSEGV),
#endif
#ifdef PR_UNALIGN_NOPRINT
    ALCOVE_CONSTANT(PR_UNALIGN_NOPRINT),
#endif
#ifdef PR_UNALIGN_SIGBUS
    ALCOVE_CONSTANT(PR_UNALIGN_SIGBUS),
#endif

#ifdef SECCOMP_FILTER_FLAG_LOG
    ALCOVE_CONSTANT(SECCOMP_FILTER_FLAG_LOG),
#endif
#ifdef SECCOMP_FILTER_FLAG_NEW_LISTENER
    ALCOVE_CONSTANT(SECCOMP_FILTER_FLAG_NEW_LISTENER),
#endif
#ifdef SECCOMP_FILTER_FLAG_SPEC_ALLOW
    ALCOVE_CONSTANT(SECCOMP_FILTER_FLAG_SPEC_ALLOW),
#endif
#ifdef SECCOMP_FILTER_FLAG_TSYNC
    ALCOVE_CONSTANT(SECCOMP_FILTER_FLAG_TSYNC),
#endif
#ifdef SECCOMP_GET_ACTION_AVAIL
    ALCOVE_CONSTANT(SECCOMP_GET_ACTION_AVAIL),
#endif
#ifdef SECCOMP_GET_NOTIF_SIZES
    ALCOVE_CONSTANT(SECCOMP_GET_NOTIF_SIZES),
#endif
#ifdef SECCOMP_MODE_DISABLED
    ALCOVE_CONSTANT(SECCOMP_MODE_DISABLED),
#endif
#ifdef SECCOMP_MODE_FILTER
    ALCOVE_CONSTANT(SECCOMP_MODE_FILTER),
#endif
#ifdef SECCOMP_MODE_STRICT
    ALCOVE_CONSTANT(SECCOMP_MODE_STRICT),
#endif
#ifdef SECCOMP_RET_ACTION
    ALCOVE_CONSTANT(SECCOMP_RET_ACTION),
#endif
#ifdef SECCOMP_RET_ACTION_FULL
    ALCOVE_CONSTANT(SECCOMP_RET_ACTION_FULL),
#endif
#ifdef SECCOMP_RET_ALLOW
    ALCOVE_CONSTANT(SECCOMP_RET_ALLOW),
#endif
#ifdef SECCOMP_RET_DATA
    ALCOVE_CONSTANT(SECCOMP_RET_DATA),
#endif
#ifdef SECCOMP_RET_ERRNO
    ALCOVE_CONSTANT(SECCOMP_RET_ERRNO),
#endif
#ifdef SECCOMP_RET_KILL
    ALCOVE_CONSTANT(SECCOMP_RET_KILL),
#endif
#ifdef SECCOMP_RET_KILL_PROCESS
    ALCOVE_CONSTANT(SECCOMP_RET_KILL_PROCESS),
#endif
#ifdef SECCOMP_RET_KILL_THREAD
    ALCOVE_CONSTANT(SECCOMP_RET_KILL_THREAD),
#endif
#ifdef SECCOMP_RET_LOG
    ALCOVE_CONSTANT(SECCOMP_RET_LOG),
#endif
#ifdef SECCOMP_RET_TRACE
    ALCOVE_CONSTANT(SECCOMP_RET_TRACE),
#endif
#ifdef SECCOMP_RET_TRAP
    ALCOVE_CONSTANT(SECCOMP_RET_TRAP),
#endif
#ifdef SECCOMP_RET_USER_NOTIF
    ALCOVE_CONSTANT(SECCOMP_RET_USER_NOTIF),
#endif
#ifdef SECCOMP_SET_MODE_FILTER
    ALCOVE_CONSTANT(SECCOMP_SET_MODE_FILTER),
#endif
#ifdef SECCOMP_SET_MODE_STRICT
    ALCOVE_CONSTANT(SECCOMP_SET_MODE_STRICT),
#endif
#ifdef SECCOMP_USER_NOTIF_FLAG_CONTINUE
    ALCOVE_CONSTANT(SECCOMP_USER_NOTIF_FLAG_CONTINUE),
#endif

    {NULL, 0}};
