/* Copyright (c) 2015, Michael Santos <michael.santos@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
static const alcove_constant_t alcove_cap_constants[] = {
#ifdef CAP_READ
    ALCOVE_CONSTANT(CAP_READ),
#endif
#ifdef CAP_WRITE
    ALCOVE_CONSTANT(CAP_WRITE),
#endif
#ifdef CAP_SEEK_TELL
    ALCOVE_CONSTANT(CAP_SEEK_TELL),
#endif
#ifdef CAP_SEEK
    ALCOVE_CONSTANT(CAP_SEEK),
#endif
#ifdef CAP_PREAD
    ALCOVE_CONSTANT(CAP_PREAD),
#endif
#ifdef CAP_PWRITE
    ALCOVE_CONSTANT(CAP_PWRITE),
#endif
#ifdef CAP_MMAP
    ALCOVE_CONSTANT(CAP_MMAP),
#endif
#ifdef CAP_MMAP_R
    ALCOVE_CONSTANT(CAP_MMAP_R),
#endif
#ifdef CAP_MMAP_W
    ALCOVE_CONSTANT(CAP_MMAP_W),
#endif
#ifdef CAP_MMAP_X
    ALCOVE_CONSTANT(CAP_MMAP_X),
#endif
#ifdef CAP_MMAP_RW
    ALCOVE_CONSTANT(CAP_MMAP_RW),
#endif
#ifdef CAP_MMAP_RX
    ALCOVE_CONSTANT(CAP_MMAP_RX),
#endif
#ifdef CAP_MMAP_WX
    ALCOVE_CONSTANT(CAP_MMAP_WX),
#endif
#ifdef CAP_MMAP_RWX
    ALCOVE_CONSTANT(CAP_MMAP_RWX),
#endif
#ifdef CAP_CREATE
    ALCOVE_CONSTANT(CAP_CREATE),
#endif
#ifdef CAP_FEXECVE
    ALCOVE_CONSTANT(CAP_FEXECVE),
#endif
#ifdef CAP_FSYNC
    ALCOVE_CONSTANT(CAP_FSYNC),
#endif
#ifdef CAP_FTRUNCATE
    ALCOVE_CONSTANT(CAP_FTRUNCATE),
#endif
#ifdef CAP_LOOKUP
    ALCOVE_CONSTANT(CAP_LOOKUP),
#endif
#ifdef CAP_FCHDIR
    ALCOVE_CONSTANT(CAP_FCHDIR),
#endif
#ifdef CAP_FCHFLAGS
    ALCOVE_CONSTANT(CAP_FCHFLAGS),
#endif
#ifdef CAP_CHFLAGSAT
    ALCOVE_CONSTANT(CAP_CHFLAGSAT),
#endif
#ifdef CAP_FCHMOD
    ALCOVE_CONSTANT(CAP_FCHMOD),
#endif
#ifdef CAP_FCHMODAT
    ALCOVE_CONSTANT(CAP_FCHMODAT),
#endif
#ifdef CAP_FCHOWN
    ALCOVE_CONSTANT(CAP_FCHOWN),
#endif
#ifdef CAP_FCHOWNAT
    ALCOVE_CONSTANT(CAP_FCHOWNAT),
#endif
#ifdef CAP_FCNTL
    ALCOVE_CONSTANT(CAP_FCNTL),
#endif
#ifdef CAP_FLOCK
    ALCOVE_CONSTANT(CAP_FLOCK),
#endif
#ifdef CAP_FPATHCONF
    ALCOVE_CONSTANT(CAP_FPATHCONF),
#endif
#ifdef CAP_FSCK
    ALCOVE_CONSTANT(CAP_FSCK),
#endif
#ifdef CAP_FSTAT
    ALCOVE_CONSTANT(CAP_FSTAT),
#endif
#ifdef CAP_FSTATAT
    ALCOVE_CONSTANT(CAP_FSTATAT),
#endif
#ifdef CAP_FSTATFS
    ALCOVE_CONSTANT(CAP_FSTATFS),
#endif
#ifdef CAP_FUTIMES
    ALCOVE_CONSTANT(CAP_FUTIMES),
#endif
#ifdef CAP_FUTIMESAT
    ALCOVE_CONSTANT(CAP_FUTIMESAT),
#endif
#ifdef CAP_LINKAT
    ALCOVE_CONSTANT(CAP_LINKAT),
#endif
#ifdef CAP_MKDIRAT
    ALCOVE_CONSTANT(CAP_MKDIRAT),
#endif
#ifdef CAP_MKFIFOAT
    ALCOVE_CONSTANT(CAP_MKFIFOAT),
#endif
#ifdef CAP_MKNODAT
    ALCOVE_CONSTANT(CAP_MKNODAT),
#endif
#ifdef CAP_RENAMEAT
    ALCOVE_CONSTANT(CAP_RENAMEAT),
#endif
#ifdef CAP_SYMLINKAT
    ALCOVE_CONSTANT(CAP_SYMLINKAT),
#endif
#ifdef CAP_UNLINKAT
    ALCOVE_CONSTANT(CAP_UNLINKAT),
#endif
#ifdef CAP_ACCEPT
    ALCOVE_CONSTANT(CAP_ACCEPT),
#endif
#ifdef CAP_BIND
    ALCOVE_CONSTANT(CAP_BIND),
#endif
#ifdef CAP_CONNECT
    ALCOVE_CONSTANT(CAP_CONNECT),
#endif
#ifdef CAP_GETPEERNAME
    ALCOVE_CONSTANT(CAP_GETPEERNAME),
#endif
#ifdef CAP_GETSOCKNAME
    ALCOVE_CONSTANT(CAP_GETSOCKNAME),
#endif
#ifdef CAP_GETSOCKOPT
    ALCOVE_CONSTANT(CAP_GETSOCKOPT),
#endif
#ifdef CAP_LISTEN
    ALCOVE_CONSTANT(CAP_LISTEN),
#endif
#ifdef CAP_PEELOFF
    ALCOVE_CONSTANT(CAP_PEELOFF),
#endif
#ifdef CAP_RECV
    ALCOVE_CONSTANT(CAP_RECV),
#endif
#ifdef CAP_SEND
    ALCOVE_CONSTANT(CAP_SEND),
#endif
#ifdef CAP_SETSOCKOPT
    ALCOVE_CONSTANT(CAP_SETSOCKOPT),
#endif
#ifdef CAP_SHUTDOWN
    ALCOVE_CONSTANT(CAP_SHUTDOWN),
#endif
#ifdef CAP_BINDAT
    ALCOVE_CONSTANT(CAP_BINDAT),
#endif
#ifdef CAP_CONNECTAT
    ALCOVE_CONSTANT(CAP_CONNECTAT),
#endif
#ifdef CAP_SOCK_CLIENT
    ALCOVE_CONSTANT(CAP_SOCK_CLIENT),
#endif
#ifdef CAP_SOCK_SERVER
    ALCOVE_CONSTANT(CAP_SOCK_SERVER),
#endif
#ifdef CAP_MAC_GET
    ALCOVE_CONSTANT(CAP_MAC_GET),
#endif
#ifdef CAP_MAC_SET
    ALCOVE_CONSTANT(CAP_MAC_SET),
#endif
#ifdef CAP_SEM_GETVALUE
    ALCOVE_CONSTANT(CAP_SEM_GETVALUE),
#endif
#ifdef CAP_SEM_POST
    ALCOVE_CONSTANT(CAP_SEM_POST),
#endif
#ifdef CAP_SEM_WAIT
    ALCOVE_CONSTANT(CAP_SEM_WAIT),
#endif
#ifdef CAP_EVENT
    ALCOVE_CONSTANT(CAP_EVENT),
#endif
#ifdef CAP_KQUEUE_EVENT
    ALCOVE_CONSTANT(CAP_KQUEUE_EVENT),
#endif
#ifdef CAP_IOCTL
    ALCOVE_CONSTANT(CAP_IOCTL),
#endif
#ifdef CAP_TTYHOOK
    ALCOVE_CONSTANT(CAP_TTYHOOK),
#endif
#ifdef CAP_PDGETPID
    ALCOVE_CONSTANT(CAP_PDGETPID),
#endif
#ifdef CAP_PDWAIT
    ALCOVE_CONSTANT(CAP_PDWAIT),
#endif
#ifdef CAP_PDKILL
    ALCOVE_CONSTANT(CAP_PDKILL),
#endif
#ifdef CAP_EXTATTR_DELETE
    ALCOVE_CONSTANT(CAP_EXTATTR_DELETE),
#endif
#ifdef CAP_EXTATTR_GET
    ALCOVE_CONSTANT(CAP_EXTATTR_GET),
#endif
#ifdef CAP_EXTATTR_LIST
    ALCOVE_CONSTANT(CAP_EXTATTR_LIST),
#endif
#ifdef CAP_EXTATTR_SET
    ALCOVE_CONSTANT(CAP_EXTATTR_SET),
#endif
#ifdef CAP_ACL_CHECK
    ALCOVE_CONSTANT(CAP_ACL_CHECK),
#endif
#ifdef CAP_ACL_DELETE
    ALCOVE_CONSTANT(CAP_ACL_DELETE),
#endif
#ifdef CAP_ACL_GET
    ALCOVE_CONSTANT(CAP_ACL_GET),
#endif
#ifdef CAP_ACL_SET
    ALCOVE_CONSTANT(CAP_ACL_SET),
#endif
#ifdef CAP_KQUEUE_CHANGE
    ALCOVE_CONSTANT(CAP_KQUEUE_CHANGE),
#endif
#ifdef CAP_KQUEUE
    ALCOVE_CONSTANT(CAP_KQUEUE),
#endif
#ifdef CAP_POLL_EVENT
    ALCOVE_CONSTANT(CAP_POLL_EVENT),
#endif
#ifdef CAP_FCNTL_GETFL
    ALCOVE_CONSTANT(CAP_FCNTL_GETFL),
#endif
#ifdef CAP_FCNTL_SETFL
    ALCOVE_CONSTANT(CAP_FCNTL_SETFL),
#endif
#ifdef CAP_FCNTL_GETOWN
    ALCOVE_CONSTANT(CAP_FCNTL_GETOWN),
#endif
#ifdef CAP_FCNTL_SETOWN
    ALCOVE_CONSTANT(CAP_FCNTL_SETOWN),
#endif
#ifdef CAP_FCNTL_ALL
    ALCOVE_CONSTANT(CAP_FCNTL_ALL),
#endif
#ifdef CAP_FCNTL_ALL
    ALCOVE_CONSTANT(CAP_FCNTL_ALL),
#endif
#ifdef CAP_IOCTLS_ALL
    ALCOVE_CONSTANT(CAP_IOCTLS_ALL),
#endif

    {NULL, 0}
};
