/* Copyright (c) 2014, Michael Santos <michael.santos@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
static const alcove_constant_t alcove_signal_constants[] = {
#ifdef SIGHUP
    ALCOVE_CONSTANT(SIGHUP),
#endif
#ifdef SIGINT
    ALCOVE_CONSTANT(SIGINT),
#endif
#ifdef SIGQUIT
    ALCOVE_CONSTANT(SIGQUIT),
#endif
#ifdef SIGILL
    ALCOVE_CONSTANT(SIGILL),
#endif
#ifdef SIGTRAP
    ALCOVE_CONSTANT(SIGTRAP),
#endif
#ifdef SIGABRT
    ALCOVE_CONSTANT(SIGABRT),
#endif
#ifdef SIGIOT
    ALCOVE_CONSTANT(SIGIOT),
#endif
#ifdef SIGBUS
    ALCOVE_CONSTANT(SIGBUS),
#endif
#ifdef SIGFPE
    ALCOVE_CONSTANT(SIGFPE),
#endif
#ifdef SIGKILL
    ALCOVE_CONSTANT(SIGKILL),
#endif
#ifdef SIGUSR1
    ALCOVE_CONSTANT(SIGUSR1),
#endif
#ifdef SIGSEGV
    ALCOVE_CONSTANT(SIGSEGV),
#endif
#ifdef SIGUSR2
    ALCOVE_CONSTANT(SIGUSR2),
#endif
#ifdef SIGPIPE
    ALCOVE_CONSTANT(SIGPIPE),
#endif
#ifdef SIGALRM
    ALCOVE_CONSTANT(SIGALRM),
#endif
#ifdef SIGTERM
    ALCOVE_CONSTANT(SIGTERM),
#endif
#ifdef SIGSTKFLT
    ALCOVE_CONSTANT(SIGSTKFLT),
#endif
#ifdef SIGCHLD
    ALCOVE_CONSTANT(SIGCHLD),
#endif
#ifdef SIGCONT
    ALCOVE_CONSTANT(SIGCONT),
#endif
#ifdef SIGSTOP
    ALCOVE_CONSTANT(SIGSTOP),
#endif
#ifdef SIGTSTP
    ALCOVE_CONSTANT(SIGTSTP),
#endif
#ifdef SIGTTIN
    ALCOVE_CONSTANT(SIGTTIN),
#endif
#ifdef SIGTTOU
    ALCOVE_CONSTANT(SIGTTOU),
#endif
#ifdef SIGURG
    ALCOVE_CONSTANT(SIGURG),
#endif
#ifdef SIGXCPU
    ALCOVE_CONSTANT(SIGXCPU),
#endif
#ifdef SIGXFSZ
    ALCOVE_CONSTANT(SIGXFSZ),
#endif
#ifdef SIGVTALRM
    ALCOVE_CONSTANT(SIGVTALRM),
#endif
#ifdef SIGPROF
    ALCOVE_CONSTANT(SIGPROF),
#endif
#ifdef SIGWINCH
    ALCOVE_CONSTANT(SIGWINCH),
#endif
#ifdef SIGIO
    ALCOVE_CONSTANT(SIGIO),
#endif
#ifdef SIGPOLL
    ALCOVE_CONSTANT(SIGPOLL),
#endif
#ifdef SIGLOST
    ALCOVE_CONSTANT(SIGLOST),
#endif
#ifdef SIGPWR
    ALCOVE_CONSTANT(SIGPWR),
#endif
#ifdef SIGSYS
    ALCOVE_CONSTANT(SIGSYS),
#endif
#ifdef SIGSTKSZ
    ALCOVE_CONSTANT(SIGSTKSZ),
#endif
    {NULL, 0}
};
