/* Copyright (c) 2015, Michael Santos <michael.santos@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#include <sys/ioctl.h>

#if defined(__linux__) || defined(__sunos__)
#else
#include <net/if.h>
#endif

static const alcove_define_t alcove_ioctl_constants[] = {
#ifdef SIOCADDRT
    ALCOVE_DEFINE(SIOCADDRT),
#endif
#ifdef SIOCDELRT
    ALCOVE_DEFINE(SIOCDELRT),
#endif
#ifdef SIOCRTMSG
    ALCOVE_DEFINE(SIOCRTMSG),
#endif
#ifdef SIOCGIFNAME
    ALCOVE_DEFINE(SIOCGIFNAME),
#endif
#ifdef SIOCSIFLINK
    ALCOVE_DEFINE(SIOCSIFLINK),
#endif
#ifdef SIOCGIFCONF
    ALCOVE_DEFINE(SIOCGIFCONF),
#endif
#ifdef SIOCGIFFLAGS
    ALCOVE_DEFINE(SIOCGIFFLAGS),
#endif
#ifdef SIOCSIFFLAGS
    ALCOVE_DEFINE(SIOCSIFFLAGS),
#endif
#ifdef SIOCGIFADDR
    ALCOVE_DEFINE(SIOCGIFADDR),
#endif
#ifdef SIOCSIFADDR
    ALCOVE_DEFINE(SIOCSIFADDR),
#endif
#ifdef SIOCGIFDSTADDR
    ALCOVE_DEFINE(SIOCGIFDSTADDR),
#endif
#ifdef SIOCSIFDSTADDR
    ALCOVE_DEFINE(SIOCSIFDSTADDR),
#endif
#ifdef SIOCGIFBRDADDR
    ALCOVE_DEFINE(SIOCGIFBRDADDR),
#endif
#ifdef SIOCSIFBRDADDR
    ALCOVE_DEFINE(SIOCSIFBRDADDR),
#endif
#ifdef SIOCGIFNETMASK
    ALCOVE_DEFINE(SIOCGIFNETMASK),
#endif
#ifdef SIOCSIFNETMASK
    ALCOVE_DEFINE(SIOCSIFNETMASK),
#endif
#ifdef SIOCGIFMETRIC
    ALCOVE_DEFINE(SIOCGIFMETRIC),
#endif
#ifdef SIOCSIFMETRIC
    ALCOVE_DEFINE(SIOCSIFMETRIC),
#endif
#ifdef SIOCGIFMEM
    ALCOVE_DEFINE(SIOCGIFMEM),
#endif
#ifdef SIOCSIFMEM
    ALCOVE_DEFINE(SIOCSIFMEM),
#endif
#ifdef SIOCGIFMTU
    ALCOVE_DEFINE(SIOCGIFMTU),
#endif
#ifdef SIOCSIFMTU
    ALCOVE_DEFINE(SIOCSIFMTU),
#endif
#ifdef SIOCSIFNAME
    ALCOVE_DEFINE(SIOCSIFNAME),
#endif
#ifdef SIOCSIFHWADDR
    ALCOVE_DEFINE(SIOCSIFHWADDR),
#endif
#ifdef SIOCGIFENCAP
    ALCOVE_DEFINE(SIOCGIFENCAP),
#endif
#ifdef SIOCSIFENCAP
    ALCOVE_DEFINE(SIOCSIFENCAP),
#endif
#ifdef SIOCGIFHWADDR
    ALCOVE_DEFINE(SIOCGIFHWADDR),
#endif
#ifdef SIOCGIFSLAVE
    ALCOVE_DEFINE(SIOCGIFSLAVE),
#endif
#ifdef SIOCSIFSLAVE
    ALCOVE_DEFINE(SIOCSIFSLAVE),
#endif
#ifdef SIOCADDMULTI
    ALCOVE_DEFINE(SIOCADDMULTI),
#endif
#ifdef SIOCDELMULTI
    ALCOVE_DEFINE(SIOCDELMULTI),
#endif
#ifdef SIOCGIFINDEX
    ALCOVE_DEFINE(SIOCGIFINDEX),
#endif
#ifdef SIOGIFINDEX
    ALCOVE_DEFINE(SIOGIFINDEX),
#endif
#ifdef SIOCSIFPFLAGS
    ALCOVE_DEFINE(SIOCSIFPFLAGS),
#endif
#ifdef SIOCGIFPFLAGS
    ALCOVE_DEFINE(SIOCGIFPFLAGS),
#endif
#ifdef SIOCDIFADDR
    ALCOVE_DEFINE(SIOCDIFADDR),
#endif
#ifdef SIOCSIFHWBROADCAST
    ALCOVE_DEFINE(SIOCSIFHWBROADCAST),
#endif
#ifdef SIOCGIFCOUNT
    ALCOVE_DEFINE(SIOCGIFCOUNT),
#endif
#ifdef SIOCGIFBR
    ALCOVE_DEFINE(SIOCGIFBR),
#endif
#ifdef SIOCSIFBR
    ALCOVE_DEFINE(SIOCSIFBR),
#endif
#ifdef SIOCGIFTXQLEN
    ALCOVE_DEFINE(SIOCGIFTXQLEN),
#endif
#ifdef SIOCSIFTXQLEN
    ALCOVE_DEFINE(SIOCSIFTXQLEN),
#endif
#ifdef SIOCDARP
    ALCOVE_DEFINE(SIOCDARP),
#endif
#ifdef SIOCGARP
    ALCOVE_DEFINE(SIOCGARP),
#endif
#ifdef SIOCSARP
    ALCOVE_DEFINE(SIOCSARP),
#endif
#ifdef SIOCDRARP
    ALCOVE_DEFINE(SIOCDRARP),
#endif
#ifdef SIOCGRARP
    ALCOVE_DEFINE(SIOCGRARP),
#endif
#ifdef SIOCSRARP
    ALCOVE_DEFINE(SIOCSRARP),
#endif
#ifdef SIOCGIFMAP
    ALCOVE_DEFINE(SIOCGIFMAP),
#endif
#ifdef SIOCSIFMAP
    ALCOVE_DEFINE(SIOCSIFMAP),
#endif
#ifdef SIOCADDDLCI
    ALCOVE_DEFINE(SIOCADDDLCI),
#endif
#ifdef SIOCDELDLCI
    ALCOVE_DEFINE(SIOCDELDLCI),
#endif
#ifdef SIOCDEVPRIVATE
    ALCOVE_DEFINE(SIOCDEVPRIVATE),
#endif
#ifdef SIOCPROTOPRIVATE
    ALCOVE_DEFINE(SIOCPROTOPRIVATE),
#endif
#ifdef FIOQSIZE
    ALCOVE_DEFINE(FIOQSIZE),
#endif
#ifdef TCGETS
    ALCOVE_DEFINE(TCGETS),
#endif
#ifdef TCSETS
    ALCOVE_DEFINE(TCSETS),
#endif
#ifdef TCSETSW
    ALCOVE_DEFINE(TCSETSW),
#endif
#ifdef TCSETSF
    ALCOVE_DEFINE(TCSETSF),
#endif
#ifdef TCGETA
    ALCOVE_DEFINE(TCGETA),
#endif
#ifdef TCSETA
    ALCOVE_DEFINE(TCSETA),
#endif
#ifdef TCSETAW
    ALCOVE_DEFINE(TCSETAW),
#endif
#ifdef TCSETAF
    ALCOVE_DEFINE(TCSETAF),
#endif
#ifdef TCSBRK
    ALCOVE_DEFINE(TCSBRK),
#endif
#ifdef TCXONC
    ALCOVE_DEFINE(TCXONC),
#endif
#ifdef TCFLSH
    ALCOVE_DEFINE(TCFLSH),
#endif
#ifdef TIOCEXCL
    ALCOVE_DEFINE(TIOCEXCL),
#endif
#ifdef TIOCNXCL
    ALCOVE_DEFINE(TIOCNXCL),
#endif
#ifdef TIOCSCTTY
    ALCOVE_DEFINE(TIOCSCTTY),
#endif
#ifdef TIOCGPGRP
    ALCOVE_DEFINE(TIOCGPGRP),
#endif
#ifdef TIOCSPGRP
    ALCOVE_DEFINE(TIOCSPGRP),
#endif
#ifdef TIOCOUTQ
    ALCOVE_DEFINE(TIOCOUTQ),
#endif
#ifdef TIOCSTI
    ALCOVE_DEFINE(TIOCSTI),
#endif
#ifdef TIOCGWINSZ
    ALCOVE_DEFINE(TIOCGWINSZ),
#endif
#ifdef TIOCSWINSZ
    ALCOVE_DEFINE(TIOCSWINSZ),
#endif
#ifdef TIOCMGET
    ALCOVE_DEFINE(TIOCMGET),
#endif
#ifdef TIOCMBIS
    ALCOVE_DEFINE(TIOCMBIS),
#endif
#ifdef TIOCMBIC
    ALCOVE_DEFINE(TIOCMBIC),
#endif
#ifdef TIOCMSET
    ALCOVE_DEFINE(TIOCMSET),
#endif
#ifdef TIOCGSOFTCAR
    ALCOVE_DEFINE(TIOCGSOFTCAR),
#endif
#ifdef TIOCSSOFTCAR
    ALCOVE_DEFINE(TIOCSSOFTCAR),
#endif
#ifdef FIONREAD
    ALCOVE_DEFINE(FIONREAD),
#endif
#ifdef TIOCINQ
    ALCOVE_DEFINE(TIOCINQ),
#endif
#ifdef TIOCLINUX
    ALCOVE_DEFINE(TIOCLINUX),
#endif
#ifdef TIOCCONS
    ALCOVE_DEFINE(TIOCCONS),
#endif
#ifdef TIOCGSERIAL
    ALCOVE_DEFINE(TIOCGSERIAL),
#endif
#ifdef TIOCSSERIAL
    ALCOVE_DEFINE(TIOCSSERIAL),
#endif
#ifdef TIOCPKT
    ALCOVE_DEFINE(TIOCPKT),
#endif
#ifdef FIONBIO
    ALCOVE_DEFINE(FIONBIO),
#endif
#ifdef TIOCNOTTY
    ALCOVE_DEFINE(TIOCNOTTY),
#endif
#ifdef TIOCSETD
    ALCOVE_DEFINE(TIOCSETD),
#endif
#ifdef TIOCGETD
    ALCOVE_DEFINE(TIOCGETD),
#endif
#ifdef TCSBRKP
    ALCOVE_DEFINE(TCSBRKP),
#endif
#ifdef TIOCSBRK
    ALCOVE_DEFINE(TIOCSBRK),
#endif
#ifdef TIOCCBRK
    ALCOVE_DEFINE(TIOCCBRK),
#endif
#ifdef TIOCGSID
    ALCOVE_DEFINE(TIOCGSID),
#endif
#ifdef TCGETS2
    //ALCOVE_DEFINE(TCGETS2),
#endif
#ifdef TCSETS2
    //ALCOVE_DEFINE(TCSETS2),
#endif
#ifdef TCSETSW2
    //ALCOVE_DEFINE(TCSETSW2),
#endif
#ifdef TCSETSF2
    //ALCOVE_DEFINE(TCSETSF2),
#endif
#ifdef TIOCGRS485
    ALCOVE_DEFINE(TIOCGRS485),
#endif
#ifdef TIOCSRS485
    ALCOVE_DEFINE(TIOCSRS485),
#endif
#ifdef TIOCGPTN
    ALCOVE_DEFINE(TIOCGPTN),
#endif
#ifdef TIOCSPTLCK
    ALCOVE_DEFINE(TIOCSPTLCK),
#endif
#ifdef TIOCGDEV
    ALCOVE_DEFINE(TIOCGDEV),
#endif
#ifdef TCGETX
    ALCOVE_DEFINE(TCGETX),
#endif
#ifdef TCSETX
    ALCOVE_DEFINE(TCSETX),
#endif
#ifdef TCSETXF
    ALCOVE_DEFINE(TCSETXF),
#endif
#ifdef TCSETXW
    ALCOVE_DEFINE(TCSETXW),
#endif
#ifdef TIOCSIG
    ALCOVE_DEFINE(TIOCSIG),
#endif
#ifdef TIOCVHANGUP
    ALCOVE_DEFINE(TIOCVHANGUP),
#endif
#ifdef FIONCLEX
    ALCOVE_DEFINE(FIONCLEX),
#endif
#ifdef FIOCLEX
    ALCOVE_DEFINE(FIOCLEX),
#endif
#ifdef FIOASYNC
    ALCOVE_DEFINE(FIOASYNC),
#endif
#ifdef TIOCSERCONFIG
    ALCOVE_DEFINE(TIOCSERCONFIG),
#endif
#ifdef TIOCSERGWILD
    ALCOVE_DEFINE(TIOCSERGWILD),
#endif
#ifdef TIOCSERSWILD
    ALCOVE_DEFINE(TIOCSERSWILD),
#endif
#ifdef TIOCGLCKTRMIOS
    ALCOVE_DEFINE(TIOCGLCKTRMIOS),
#endif
#ifdef TIOCSLCKTRMIOS
    ALCOVE_DEFINE(TIOCSLCKTRMIOS),
#endif
#ifdef TIOCSERGSTRUCT
    ALCOVE_DEFINE(TIOCSERGSTRUCT),
#endif
#ifdef TIOCSERGETLSR
    ALCOVE_DEFINE(TIOCSERGETLSR),
#endif
#ifdef TIOCSERGETMULTI
    ALCOVE_DEFINE(TIOCSERGETMULTI),
#endif
#ifdef TIOCSERSETMULTI
    ALCOVE_DEFINE(TIOCSERSETMULTI),
#endif
#ifdef TIOCMIWAIT
    ALCOVE_DEFINE(TIOCMIWAIT),
#endif
#ifdef TIOCGICOUNT
    ALCOVE_DEFINE(TIOCGICOUNT),
#endif
#ifdef TIOCPKT_DATA
    ALCOVE_DEFINE(TIOCPKT_DATA),
#endif
#ifdef TIOCPKT_FLUSHREAD
    ALCOVE_DEFINE(TIOCPKT_FLUSHREAD),
#endif
#ifdef TIOCPKT_FLUSHWRITE
    ALCOVE_DEFINE(TIOCPKT_FLUSHWRITE),
#endif
#ifdef TIOCPKT_STOP
    ALCOVE_DEFINE(TIOCPKT_STOP),
#endif
#ifdef TIOCPKT_START
    ALCOVE_DEFINE(TIOCPKT_START),
#endif
#ifdef TIOCPKT_NOSTOP
    ALCOVE_DEFINE(TIOCPKT_NOSTOP),
#endif
#ifdef TIOCPKT_DOSTOP
    ALCOVE_DEFINE(TIOCPKT_DOSTOP),
#endif
#ifdef TIOCPKT_IOCTL
    ALCOVE_DEFINE(TIOCPKT_IOCTL),
#endif
#ifdef TIOCSER_TEMT
    ALCOVE_DEFINE(TIOCSER_TEMT),
#endif
    {NULL, 0}
};
